export const GET_ERRORS = 'GET_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const LOAD_SUBREDDIT = 'LOAD_SUBREDDIT';
export const SET_SUBREDDIT_LOADING = 'SET_SUBREDDIT_LOADING';

export const GET_POST = 'GET_POST';
export const GET_POSTS = 'GET_POSTS';
export const SET_POST_LOADING = 'SET_POST_LOADING';
export const GET_AMOUNT = 'GET_AMOUNT';

export const GET_PROFILE = 'GET_PROFILE';
export const NO_PROFILE = 'NO_PROFILE';
export const SET_PROFILE_LOADING = 'SET_PROFILE_LOADING';